name: First Workflow

on:
  - push

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps:
            - name: Welcome Message
              run: echo "My first GitHub Actions Job"

            - name: List Files 
              run: ls -a

            - name: Print Working Directory
              run: pwd
            - name: Exit message
              run: echo "Done, exiting............"
