name: Docker Workflow

on:
  push:

env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: resume-app

permissions:
  id-token: write
  contents: write
  packages: write

jobs: 
  docker_build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login to DockerHub
        run: docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build and Tag for DockerHub and GHCR
        run: |
          # Build and tag the Docker image
          docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest .
          
          # Tag the image for GitHub Container Registry (GHCR)
          docker tag ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest ghcr.io/miss_gloria/${{ env.IMAGE_NAME }}:latest

      - name: Publish Image to DockerHub
        run: docker push ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: GHCR Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Image to GHCR
        run: docker push ghcr.io/miss_gloria/${{ env.IMAGE_NAME }}:latest
