name: Docker Workflow

on:
  push:

env:
  CONTAINER_REGISTRY: ghcr.io
  IMAGE_NAME: resume-app
  REPOSITORY: miss_gloria  # Ensure this is correct

permissions:
  contents: write
  packages: write

jobs: 
  docker_build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build and Tag
        run: |
          docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest .
          docker tag ${{ env.CONTAINER_REGISTRY }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest

      - name: Push Image to GHCR
        run: docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
